name: Test

on:
  - push
  - pull_request

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test errexit
        run: |
          echo first
          bash -c 'exit 0'
          echo second
          bash -c 'exit 1'
          echo third
